apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
      - name: petclinic
        image: nada_essam/petclinic-service-:latest 
        ports:
        - containerPort: 8083
