apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: petclinic
        image: nada_essam/petclinic-service-b:latest 
        ports:
        - containerPort: 8082
